BEGIN TRANSACTION;
CREATE TABLE User (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	nic varchar(255),
	karma double,
	rating double
);
CREATE TABLE Post (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
author_id INTEGER NOT NULL,
post_name varchar(255),
post_rating INTEGER,
views INTEGER,
stars INTEGER
coments_num INTEGER,
ouner_coments INTEGER,
 FOREIGN KEY(author_id) REFERENCES User(id)
);
CREATE TABLE Coments (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
post_id INTEGER,
user_id INTEGER,
FOREIGN KEY(post_id) REFERENCES Post(id),
FOREIGN KEY(user_id) REFERENCES User(id)
);
COMMIT;
